// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TodoList_blazor.API.Model;

#nullable disable

namespace TodoList_blazor.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230807104336_tododb")]
    partial class tododb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TodoList_blazor.Shared.Do", b =>
                {
                    b.Property<int>("DoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DoId"));

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<string>("DoString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DoId");

                    b.ToTable("Dos");

                    b.HasData(
                        new
                        {
                            DoId = 1,
                            Completed = false,
                            DoString = "item 1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
